### ISSUE TITLE
Offer a way to configure which chromium to use for feature that rely on it (diagram snapshot)

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10170]
This is a macro issue that should solve all the report 

- [ ] https://github.com/quarto-dev/quarto-cli/issues/2980
- [ ] https://github.com/quarto-dev/quarto-cli/issues/4648
- [x] https://github.com/quarto-dev/quarto-cli/issues/10162

For reference, current state in some R package that also need to use chromium (as discussed in https://github.com/quarto-dev/quarto-cli/issues/4648#issuecomment-1458980938)

* [`pagedown::find_chrome()`](https://github.com/rstudio/pagedown/blob/6f27778df1acf592206a5a06d01ced04b2d2e0d1/R/chrome.R#L301-L330)  will look for chrome for each OS, on Linux checking for `c('google-chrome', 'chromium-browser', 'chromium', 'google-chrome-stable')` and using first found. Setting env var `PAGEDOWN_CHROME` allow to specific a specific one to use 
* [`chromote::find_chrome()`](https://github.com/rstudio/chromote/blob/e1d2997932671642d12bef0b4c58611e322035c7/R/chrome.R#L41-L81) will so similarly, looking for `google-chrome`, `chromium-browser` and `chromium` , or using `CHROMOTE_CHROME` if set.
            

Having a `QUARTO_CHROMIUM` environment variable to look for, and use this path if set seems a good solution.

**Comment by ralmond** [comment]
This looks like a good solution.  It would be useful to add a help file or a link to a web page which shows possible places to look for chromium installation, as I suspect that not all users experiencing this problem will know all of the places to look.
