### ISSUE TITLE
Epic: Ongoing Chores

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#10773]
This is for 1.7:

- [ ] Inventory our ongoing exposure to "expiring objects" (specifically, certs and developer accounts)
- [ ] Create calendar items
- [ ] Get our deno issues in shape, because Deno 2 is right around the corner
  - [ ] This will trigger more bundling problems, because `deno bundle` goes away in Deno 2
- [ ] Dependency refresh automation?
