### ISSUE TITLE
booleans in `meta` variable for lua filters end up as `Str "nil"`

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#1887]
### Bug description

Given a yml header

```yml
test:
  var1: true
  var2: false
  var3: hello
```

and a shortcode making use of the `meta` variable (https://quarto.org/docs/extensions/shortcodes.html#example-metadata-options):

```lua
quarto.utils.dump(meta['test.var1'])
quarto.utils.dump(meta['test.var2'])
quarto.utils.dump(meta['test.var3'])
if meta['test.var2'] then
  quarto.utils.dump('this should not print')
end
```
Results in

```
1: Str "nil"
1: Str "nil"
1: Str "hello"
this should not print
```

### `quarto check` Output

I'm on `commit ca55431fb3e417162025192b5252b7968fd1773e`

```bash
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/jannik/sw/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /usr/bin/python3
      Jupyter: 4.11.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /home/jannik/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
(|) Inspecting toolsCheck file:///home/jannik/sw/quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
[✓] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     v2022.05      v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here: https://github.com/quarto-dev/quarto-cli/commit/912d5355b17e4871edd5769af74c6c74ff35b492
