### ISSUE TITLE
Table pushes text into bottom margin/off page

### ISSUE THREAD

**Issue by clabornd** [quarto-dev/quarto-cli#4790]
### Bug description

Ubuntu 20.04, running the below file from vscode's render causes the text at the bottom of this file to run off the bottom of the page.  A new page is not created, If I put, say, a plot on the next page to force a new page, the text still does not appear.  Removing the second table seems to fix things.

````
---
title: "Tables trouble"
author: "Daniel Claborne"
format:
    pdf
engine: knitr
execute:
    echo: false
    message: false
    warning: false
editor: visual
---

## A HEADER!

### such header

Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

```{r}
#| label: fig-ggplot
#| fig-cap: "a plot that is very good"
library(ggplot2)
library(knitr)

ggplot(aes(x = 1:1000, y = 1:1000), data = NULL) + geom_point()
```

### header3[^asdf]

**boldtext**
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur. @tbl-tab1

[^asdf]:  footnote

```{r}
#| label: tbl-tab1
#| tbl-cap: "a table using kable"
 
kable(table(c(1,2,3), c(1,2,3)), row.names = TRUE)
```

**b)**
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur. @tbl-tab2

<!-- ```{r}
#| label: tbl-tab2
#| tbl-cap: "A pipe table"
cmatrix = data.frame(
    "1" = c(7, 0, 5, 2),
    "2" = c(0, 20, 0, 1),
    "3" = c(0, 0, 62, 27),
    "4" = c(0, 0, 2, 9),
    check.names = FALSE
)

rownames(cmatrix) = c("1", "2", "3", "4")
kable(cmatrix, row.names = TRUE)
``` -->

|   | 1 | 2  | 3  | 4 |
|---|---|----|----|---|
| 1 | 7 | 0  | 5  | 0 |
| 2 | 0 | 20 | 1  | 0 |
| 3 | 0 | 0  | 62 | 2 |
| 4 | 2 | 1  | 27 | 9 |

: A pipe table {#tbl-tab2}
  
## Wow, now thats a header
  
**part 1**

Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
  
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections [TEXT IS CUT OFF APPROXIMATELY HERE aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAA


````
### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
In local testing with that document, I'm not seeing the issue, though perhaps I am misunderstanding what the problem is. When I render and preview that document, here is what appears for me (MacOS, not Ubuntu, in case it is platform specific):

![Screenshot 2023-03-13 at 9 09 45 AM](https://user-images.githubusercontent.com/261654/224711360-1ed79f8f-306f-4d18-8dd9-49ef117b53e7.png)

Other than the line not breaking due to no whitespace I'm not seeing the issue. Can you share what you're seeing / or if this is showing the issue maybe point me at it as I'm still missing it.

**Comment by clabornd** [comment]
Hi, thanks for the quick response, below is an example of what I'm experiencing:

![Screenshot from 2023-03-13 10-38-10](https://user-images.githubusercontent.com/31082141/224783609-1ec14c6f-bade-4010-b12c-e508583eb6a0.png)

This is scrolled all the way to the bottom of the second of 2 pages.  You can see the page number floating in the middle of the sea of text there that goes off the page.

In case this output from quarto is relevant:

```
pandoc 
  to: latex
  output-file: test-tables.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Tables trouble
  author: Daniel Claborne
  editor: visual
  
running xelatex - 1
  This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/Debian) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 2
  This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/Debian) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
```

**Comment by cscheid** [comment]
Can you run `quarto check` and give us the output? Thanks!

**Comment by clabornd** [comment]
```
[✓] Checking Quarto installation......OK
      Version: 1.2.313
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.7.6 (Conda)
      Path: /home/daniel/anaconda3/bin/python
      Jupyter: 4.11.2
      Kernels: medalla-viz, python3, torch2, ml4t, omscs, isye8803, isye, omscs37, base

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /usr/lib/R
      LibPaths:
        - /home/daniel/R/x86_64-pc-linux-gnu-library/4.2
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.16

[✓] Checking Knitr engine render......OK
```

**Comment by dragonstyle** [comment]
Unfortunately, I still cannot reproduce this in Ubuntu (though 22.04).

![Screenshot 2023-03-14 at 12 15 27 PM](https://user-images.githubusercontent.com/261654/225069398-fc71957a-c235-4439-8c56-abde9c3dd845.png)

I'm not sure what explains the difference :(. I am testing using the latest version of Quarto (1.3.x) rather than 1.2, but I'm not aware of changes that we've made that would account for a different in this behavior.

One other thought - you could enable `keep-tex` in your front matter and we could compare the text output to try to see whether we're generating different TeX which could account for the different. Here is the TeX output from my testing:

```latex
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\KOMAoption{captions}{tableheading}
\makeatletter
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Tables trouble},
  pdfauthor={Daniel Claborne},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Tables trouble}
\author{Daniel Claborne}
\date{}

\begin{document}
\maketitle
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[frame hidden, boxrule=0pt, interior hidden, borderline west={3pt}{0pt}{shadecolor}, enhanced, sharp corners, breakable]}{\end{tcolorbox}}\fi

\hypertarget{a-header}{%
\subsection{A HEADER!}\label{a-header}}

\hypertarget{such-header}{%
\subsubsection{such header}\label{such-header}}

Contrary to popular belief, Lorem Ipsum is not simply random text. It
has roots in a piece of classical Latin literature from 45 BC, making it
over 2000 years old. Richard McClintock, a Latin professor at
Hampden-Sydney College in Virginia, looked up one of the more obscure
Latin words, consectetur, from a Lorem Ipsum passage, and going through
the cites of the word in classical literature, discovered the
undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33
of ``de Finibus Bonorum et Malorum'' (The Extremes of Good and Evil) by
Cicero, written in 45 BC. This book is a treatise on the theory of
ethics, very popular during the Renaissance. The first line of Lorem
Ipsum, ``Lorem ipsum dolor sit amet..'', comes from a line in section
1.10.32.

\begin{figure}

{\centering \includegraphics{test_files/figure-pdf/fig-ggplot-1.pdf}

}

\caption{\label{fig-ggplot}a plot that is very good}

\end{figure}

\hypertarget{header3asdf}{%
\subsubsection[header3]{\texorpdfstring{header3\footnote{footnote}}{header3}}\label{header3asdf}}

\textbf{boldtext} Contrary to popular belief, Lorem Ipsum is not simply
random text. It has roots in a piece of classical Latin literature from
45 BC, making it over 2000 years old. Richard McClintock, a Latin
professor at Hampden-Sydney College in Virginia, looked up one of the
more obscure Latin words, consectetur. Table~\ref{tbl-tab1}

\hypertarget{tbl-tab1}{}
\begin{longtable}[]{@{}lrrr@{}}
\caption{\label{tbl-tab1}a table using kable}\tabularnewline
\toprule()
& 1 & 2 & 3 \\
\midrule()
\endfirsthead
\toprule()
& 1 & 2 & 3 \\
\midrule()
\endhead
1 & 1 & 0 & 0 \\
2 & 0 & 1 & 0 \\
3 & 0 & 0 & 1 \\
\bottomrule()
\end{longtable}

\textbf{b)} Contrary to popular belief, Lorem Ipsum is not simply random
text. It has roots in a piece of classical Latin literature from 45 BC,
making it over 2000 years old. Richard McClintock, a Latin professor at
Hampden-Sydney College in Virginia, looked up one of the more obscure
Latin words, consectetur. Table~\ref{tbl-tab2}

\hypertarget{tbl-tab2}{}
\begin{longtable}[]{@{}lllll@{}}
\caption{\label{tbl-tab2}A pipe table}\tabularnewline
\toprule()
& 1 & 2 & 3 & 4 \\
\midrule()
\endfirsthead
\toprule()
& 1 & 2 & 3 & 4 \\
\midrule()
\endhead
1 & 7 & 0 & 5 & 0 \\
2 & 0 & 20 & 1 & 0 \\
3 & 0 & 0 & 62 & 2 \\
4 & 2 & 1 & 27 & 9 \\
\bottomrule()
\end{longtable}

\hypertarget{wow-now-thats-a-header}{%
\subsection{Wow, now thats a header}\label{wow-now-thats-a-header}}

\textbf{part 1}

Contrary to popular belief, Lorem Ipsum is not simply random text. It
has roots in a piece of classical Latin literature from 45 BC, making it
over 2000 years old. Richard McClintock, a Latin professor at
Hampden-Sydney College in Virginia, looked up one of the more obscure
Latin words, consectetur, from a Lorem Ipsum passage, and going through
the cites of the word in classical literature, discovered the
undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33
of ``de Finibus Bonorum et Malorum'' (The Extremes of Good and Evil) by
Cicero, written in 45 BC. This book is a treatise on the theory of
ethics, very popular during the Renaissance. The first line of Lorem
Ipsum, ``Lorem ipsum dolor sit amet..'', comes from a line in section
1.10.32.

Contrary to popular belief, Lorem Ipsum is not simply random text. It
has roots in a piece of classical Latin literature from 45 BC, making it
over 2000 years old. Richard McClintock, a Latin professor at
Hampden-Sydney College in Virginia, looked up one of the more obscure
Latin words, consectetur, from a Lorem Ipsum passage, and going through
the cites of the word in classical literature, discovered the
undoubtable source. Lorem Ipsum comes from sections {[}TEXT IS CUT OFF
APPROXIMATELY HERE
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAA



\end{document}
```

**Comment by clabornd** [comment]
Yea I get the same output, and building it from a TeX GUI produces the same bad output, so this is probably just something with my tex installation...I'll try updating/reinstalling and see if it fixes things but I think this can be closed.

**Comment by clabornd** [comment]
Fixed by updating to TexLive 2022 https://www.tug.org/texlive/acquire-netinstall.html instead of the 2019 version installed with `sudo apt install texlive` on Ubuntu 20.04.  Sorry for the goose chase.

**Comment by dragonstyle** [comment]
Thanks for sharing the outcome - good to know another place to double check next time and glad things are working better now...
