### ISSUE TITLE
Email Integration

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#4946]
Work for this is being done as a Quarto extension in the `https://github.com/rich-iannone/quarto-email` repository (private for now). The email body will be in a div with class `"email"`.

To make this work with the Connect emailing system, the main goal, the filter needs to generate a JSON file in the working directory with specific key names. Connect will be updated to watch for this file; this is close to the blastula/Connect model where R Markdown metadata is captured when certain key-value pairs are present. 
```[tasklist]
### Tasks
- [x] add `attachments` as resources
- [x] test email messages with various image types
- [x] test email messages with external (web) images
```
