### ISSUE TITLE
Could you support PAT for authentication on on-prem Confluence?

### ISSUE THREAD

**Issue by mwouts** [quarto-dev/quarto-cli#5017]
### Bug description

It is really exciting to see `quarto` addressing the challenge of publishing content to Confluence!

I gave it a try but unfortunately I have not been able to connect to my on-prem Confluence.
This seems to be because on-prem versions of confluence do not have API tokens.

Instead they have personal access tokens ([PAT](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html)).

Do you think you could support PAT, in addition to API tokens?

Note that I have tried passing a PAT instead of the expected API token but that did not work (the error was `"x-seraph-loginreason": "AUTHENTICATED_FAILED"`, and I was using `quarto-1.3.290`)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by allenmanning** [comment]
Thanks for posting this.  

We made this decision early on in the development to only focus on Confluence Cloud as Atlassian is EoLing Confluence Server in favor of Cloud.

More information on this can be found here: https://www.atlassian.com/migration/assess/journey-to-cloud.

I'm curious if your current On Prem installation has plans for migration to Cloud, and if so what is the timeframe.

Related request: https://github.com/quarto-dev/quarto-cli/issues/4846

**Comment by matthewdwood82** [comment]
> ### Bug description
> It is really exciting to see `quarto` addressing the challenge of publishing content to Confluence!
> 
> I gave it a try but unfortunately I have not been able to connect to my on-prem Confluence. This seems to be because on-prem versions of confluence do not have API tokens.
> 
> Instead they have personal access tokens ([PAT](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html)).
> 
> Do you think you could support PAT, in addition to API tokens?
> 
> Note that I have tried passing a PAT instead of the expected API token but that did not work (the error was `"x-seraph-loginreason": "AUTHENTICATED_FAILED"`, and I was using `quarto-1.3.290`)
> 
> ### Checklist
> * [ ]  Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
> * [ ]  Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
> * [ ]  Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
> * [ ]  Please document the operating system you're running. If on Linux, please provide the specific distribution.
> * [ ]  Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

Are you trying to identify a different authentication path, and asking about a specific one? We have an instance of Confluence Data Center on-prem and I am running into similar issues on authentication. 

If I had a better sense for what is _not_ supported in Server, I have folks in my org that are willing to explore what might be needed in order to publish to an on-prem instance.

**Comment by matthewdwood82** [comment]
Thanks @mwouts for passing example `curl` calls. Will forward along to our IT folks and see what insights they might have.

**Comment by mwouts** [comment]
You're welcome @matthewdwood82 .

By the way it seems that the authentication string is created here:
https://github.com/quarto-dev/quarto-cli/blob/5ca37a380466b974669ac0c4346b79c7fbd1c672/src/publish/confluence/api/index.ts#L305-L310

I have tried to change it to make it more similar to the `curl` example (which worked) [see this [SO question](https://stackoverflow.com/questions/64164935/authorization-bearer-token-header-in-javascript)] but all I got was a different error: `Error: Unable to sign into Confluence account: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`
instead of the original error `Error: Unable to sign into Confluence account: 401 - Unauthorized`

**Comment by matthewdwood82** [comment]
> You're welcome @matthewdwood82 .
> 
> By the way it seems that the authentication string is created here:
> 
> https://github.com/quarto-dev/quarto-cli/blob/5ca37a380466b974669ac0c4346b79c7fbd1c672/src/publish/confluence/api/index.ts#L305-L310
> 
> I have tried to change it to make it more similar to the `curl` example (which worked) [see this [SO question](https://stackoverflow.com/questions/64164935/authorization-bearer-token-header-in-javascript)] but all I got was a different error: `Error: Unable to sign into Confluence account: Unexpected token '<', "<!DOCTYPE "... is not valid JSON` instead of the original error `Error: Unable to sign into Confluence account: 401 - Unauthorized`

That's helpful, thanks! DOCTYPE makes it seem to me that something is trying to pass XML when JSON is required. Are you sending that (as part of PAT) or is something else happening? If the former, maybe try escaping that `<` character with `\` or `\\` and try again?

**Comment by mwouts** [comment]
I can get rid of the `not valid JSON` error by using ```Authorization: `Bearer ${token}` ``` **and** `Confluence Domain: > https://confluence.mysite.com/rest/api/content`. However if I do so the next error is
```
(|) Verifying account...ERROR: 
[Confluence] [General] response.status !== 200 Response {
  body: ReadableStream { locked: false },
  bodyUsed: false,
  headers: Headers {
  "cache-control": "no-transform",
  "content-type": "application/json",
  date: "Mon, 03 Apr 2023 05:41:47 GMT",
  "set-cookie": "JSESSIONID=xxx; Path=/; HttpOnly",
  "transfer-encoding": "chunked",
  vary: "User-Agent",

  "x-content-type-options": "nosniff",
  "x-seraph-loginreason": "OK"
},
  ok: false,
  redirected: false,
  status: 404,
  statusText: "Not Found",
  url: "https://confluence.mysite.com/rest/api/content/wiki/rest/api/user/current?expand=operations"
}
[✓] Verifying account...
ERROR: Unable to sign into Confluence account: 404 - Not Found
```

My understanding of this is that the URL suffix `wiki/rest/api/user/current?expand=operations` that is appended to `https://confluence.mysite.com/rest/api/content/` is specific to Confluence Cloud. So that answers my initial question, it is probably not enough to fix authentication to get `quarto publish` work with on-prem confluence. Given this is not the direction chosen by Confluence/Quarto-dev I will therefore close this issue. Thanks anyway for taking the time to answer this!
