### ISSUE TITLE
Documentation Corrections

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#5188]
An epic on issues that require small (at most adding a paragraph) **corrections** to the docs:

- [x] https://github.com/quarto-dev/quarto-cli/issues/4462
- [x] https://github.com/quarto-dev/quarto-cli/issues/2306
- [x] https://github.com/quarto-dev/quarto-cli/issues/4954
- [x] https://github.com/quarto-dev/quarto-cli/issues/4518
- ~[ ] https://github.com/quarto-dev/quarto-cli/issues/4519~ Move to part of GH Pages refresh
- [x] https://github.com/quarto-dev/quarto-cli/issues/5243

**Comment by cwickham** [comment]
All items completed
