### ISSUE TITLE
1.4 dependency refresh

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#5429]
- [x] observablehq (up to 5.5.1) (#5320)
- [x] mermaid (up to 10.0.2) (#5322)
- [x] deno (up to 1.33.1) (#5247)
  - [x] stdlib vendoring (up to 0.185.0)
  - [x] decide what needs to happen with `import 'node:...'`
  - [x] decide what to do with unsupported `safe: true` in dotenv.ts
  - [x] ~~fix our dependence on `deno bundle`~~ make sure we can `deno bundle` for now
- [ ] revealjs (up to 4.4.0)
	- [ ] update plugins

## Other dependencies from `./configuration`

```
export DENO_DOM=v0.1.35-alpha-artifacts
export DARTSASS=1.55.0
export ESBUILD=0.15.6
export BOOTSTRAP=ec93879c66ddf48ceec7ecf35401bdf0a93a0a77
export BOOTSTRAP_FONT=1.10.0
export BOOTSWATCH=5.2.2
export ANCHOR_JS=4.3.1
export POPPER_JS=2.11.4
export CLIPBOARD_JS=2.0.11
export TIPPY_JS=6.3.7
export PDF_JS=2.8.335
export REVEAL_JS_MENU=2.1.0
export REVEAL_JS_CHALKBOARD=a88c134e2cf3c7780448db003e7329c3cbd8cfb4
export REVEAL_JS_PDFEXPORT=2.0.1
export LIST_JS=2.3.1
export DAY_JS=1.11.6
export ZENSCROLL_JS=4.0.2
export GITHUB_MARKDOWN_CSS=5.2.0
export AUTOCOMPLETE_JS=1.7.3
export FUSE_JS=6.6.2
export ALGOLIA_SEARCH_JS=4.5.1
export ALGOLIA_SEARCH_INSIGHTS_JS=2.0.3
```

**Comment by cscheid** [comment]
@cderv Do you think you could take a look at whether refreshing `revealjs` is a good idea for our 1.4 release?

**Comment by cderv** [comment]
We'll do it in 1.5. This is tracked at 
* https://github.com/quarto-dev/quarto-cli/issues/4795
