### ISSUE TITLE
quarto-title-meta not affected by page-layout

### ISSUE THREAD

**Issue by KaiWaldrant** [quarto-dev/quarto-cli#5431]
### Bug description

When adding a `title-block-banner` the `.quarto-title-meta` div is not affected by the `page-layout: full`. The issue is reproduced here:  <https://github.com/KaiWaldrant/quarto-title-meta>. This has also been tested on the latest nightly build. I've also searched the issues but could not find a related one.

result:
![image](https://user-images.githubusercontent.com/80908902/236384816-3f116387-4b8e-4db4-bdd6-46af014d3a45.png)

expected:
![image](https://user-images.githubusercontent.com/80908902/236384873-d0f109fa-4143-4b27-b279-28ac04327872.png)

reference (without `title-block-banner: black`):
![image](https://user-images.githubusercontent.com/80908902/236385110-fc5ba24f-59ba-4c99-9de4-dfd2ad197ad3.png)

qmd file used:
```markdown
---
title: "quarto-title-meta"
title-block-banner-color: white
title-block-banner: black
page-layout: full
date: "2021/09"
date-format: "MMMM, YYYY"
author: Kai Waldrant
categories:
  - competition
  - code
---

:::{layout="[[30,70]]"}
::::{.section-header}
## Summary
::::

::::{.section-content}
Scaling from a dozen cells a decade ago to millions of cells today, single-cell measurement technologies are driving a revolution in the life sciences. Recent advances make it possible to measure multiple high-dimensional modalities (e.g. DNA accessibility, RNA, and proteins) simultaneously in the same cell. Such data provides, for the first time, a direct and comprehensive view into the layers of gene regulation that drive biological diversity and disease.

In this competition for [NeurIPS 2021,](https://neurips.cc/Conferences/2021/CompetitionTrack) we present three tasks on multimodal single-cell data using a first-of-its-kind multi-omics benchmarking dataset. Teams will predict one modality from another and learn representations of multiple modalities measured in the same cells. Progress will reveal how a common genetic blueprint gives rise to distinct cell types and processes, as a foundation for improving human health.

{{< video https://www.youtube.com/embed/y5YbM0tbvCo >}}

To learn more, you can watch a [lecture](https://www.youtube.com/watch?v=ZXDILOyiy7A) presented at the Broad Institute's Models Inferences and Algorithms meeting (<a href="https://drive.google.com/file/d/1olW-WN-kHYuG15MSgAK3GUqNtMCPFBq3/view?usp=sharing" style="color: #EB5252;">slides</a>).
::::
:::
``` 

os: fedora 37

quarto check:
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /home/kai/opt/quarto-1.3.340/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /home/kai/anaconda3/bin/python
      Jupyter: 5.2.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /usr/lib64/R
      LibPaths:
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: (None)
      rmarkdown: (None)

      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
``` 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
