### ISSUE TITLE
Meta shortcode in code blocks no longer respect end of line

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#5490]
### Bug description

Taking a smaller example based on the documentation website:

````qmd
---
format: html
provider: gh-pages
---

```yaml
{{< meta provider >}}
workflow_dispatch:
```
````

| 1.3.340 | dev |
|:-------:|:---:|
| <img width="217" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/e97f2cee-bdde-42b9-be75-ddcf7d3cf79e"> | <img width="311" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/127a1769-9917-48cc-b273-657c9c35cd52"> |

Issue initially observed in https://github.com/quarto-dev/quarto-web/edit/main/docs/publishing/github-pages.qmd (https://quarto.org/docs/publishing/github-pages.html#publish-action)

---

Using VSCode on MacOS Apple Silicon chip

<img width="1436" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/85667819-566d-458e-8226-c1b4b788fe06">

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
Issue is no longer there on the website.
