### ISSUE TITLE
GitHub Pages Docs

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#6204]
Issues that relate to our [Publishing to GitHub Pages](https://quarto.org/docs/publishing/github-pages.html) docs:

- [x] https://github.com/quarto-dev/quarto-cli/issues/5686.
- [x] https://github.com/quarto-dev/quarto-cli/issues/4498
- [x] https://github.com/quarto-dev/quarto-cli/issues/4941
- [x] https://github.com/quarto-dev/quarto-cli/issues/4519
- [x] https://github.com/quarto-dev/quarto-cli/issues/2994

**Comment by cwickham** [comment]
All complete/

**Comment by mcanouil** [comment]
@cwickham think some of the elements in the sub-issues were left out because closed for partial resolution.

Publishing to GitHub Pages still does not need or create `_publish.yml`.

- https://quarto.org/docs/publishing/github-pages.html#publish-action
