### ISSUE TITLE
[1.4 Docs] Updates based on changelog-1.4.md

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#7906]
A list of things from the changelog that I think need a mention in the Guide (or other appropriate section of quarto.org) and aren't already in the 1.4 Highlights.

As of commit ~53fca91~ ~78023ec29fbb6e420659ca6d4aa382d3d6e04668~ 536f6073835f29efe25a6c52ca14cfa024743400

## Breaking Changes

- [x] In website projects, a single sidebar with a `id` property will no longer be used as a global sidebar. It will instead be used as a sidebar for only pages which specify that `id` or pages linked to from the sidebar.

## HTML Format

- [x] Add support for showing cross reference contents on hover (use `crossrefs-hover: false` to disable).
- [x] Add support for displaying `keywords` in HTML page title block, when present.
- [x] ([#3473](https://github.com/quarto-dev/quarto-cli/issues/3473)): Add support for `body-right` and `body-left` layouts for Website Table of Contents.
- [X] ~([#4840](https://github.com/quarto-dev/quarto-cli/issues/4840)): Add support for specifying a custom Hypothesis client url using `client-url`~ No change beyond fixing link to ref page where this option is documented.
- [X] ~([#4882](https://github.com/quarto-dev/quarto-cli/issues/4882)): Add support for `canonical-url`, which when provided will include a link tag with rel='canonical' which will use an explictly provided or automatically generated canonical url for the document.~
- [x] ([#7187](https://github.com/quarto-dev/quarto-cli/issues/7187)): Add `html-table-processing: none` to document- and project-level metadata to disable HTML table processing. Add `{html-table-processing="none"}` to a fenced div to disable HTML table processing for the elements in that div. Add `html-table-processing: none` on knitr or jupyter cell to disable HTML table processing for the cell output content.

## RevealJS Format

- [ ] ([#1943](https://github.com/quarto-dev/quarto-cli/issues/1943)): Allow setting `code-block-height` in presentation front matter.
- ([#7134](https://github.com/quarto-dev/quarto-cli/issues/7134)): `.nostrech` can now be applied on image directly to opt-out Revealjs' image stretching when `auto-stretch: true` (the default).

## PDF Format

- [x] ([#5058](https://github.com/quarto-dev/quarto-cli/issues/5058)): Add a `before-title.tex` partial to the PDF format. This partial will appear in the document premable just before the title block, allowing further customization of the document preamble. By default, this partial is empty.

## Website Listings

- [ ] Add support for programmatically filtering content from a listing using `include` or `exclude` with glob syntax to include or exclude specific items from the listing. See <https://github.com/quarto-dev/quarto-cli/commit/d415d9ca5b7cb59a8a4750dd3eeb60116b931bd6s>
- [ ] ([#6407](https://github.com/quarto-dev/quarto-cli/issues/6407)): Add supporting for the field `word-count` for listing items. It is not displayed by default.
- [ ] ~([#4800](https://github.com/quarto-dev/quarto-cli/issues/4800)): Add support for including an `xml-stylesheet` in listings. Use the `xml-stylesheet: example.xsl` under `feed:` to provide a path to an XSL style sheet to style your RSS feed.~ Make sure it's in reference.
- [ ] ([#7290](https://github.com/quarto-dev/quarto-cli/issues/7290)): Add support for `feed:type` of `metadata`, which will use only explicitly provided description metadata when generating an RSS feed. Additionally, note that `partial` feed types will prefer to use an explicit description over the first paragraph, when a description is available. *Add entry in table in Guide, check its in Reference*

## Websites

- [x] Add support for `navbar > toggle-position` to control whether the responsive navbar toggle appears on the right or the left.
- [x] Add support for setting `page-navigation: true|false` in either a page or in `_metadata.yml`. This allows individual pages or sections of a website to control whether `page-navigaation` appears.
- [x] Add support for `bread-crumbs: true|false` to control whether bread crumbs are displayed. Add support for display of breadcrumbs on full width (non-mobile) pages when `bread-crumbs` is true. Default value is true.
- [x] ([#5283](https://github.com/quarto-dev/quarto-cli/issues/5283)): Add support for setting `repo-actions: false` in a document to prevent the display of repository actions on a specific page.
- [x] ([#5964](https://github.com/quarto-dev/quarto-cli/issues/5964)): Add support for `repo-link-target` and `repo-link-rel` to control the corresponding attributes of repo-action links.
- [x] Add support for `show-item-context` key within the `search` key to control whether page parents are display next to items in search results. Pass `tree`, `parent`, `root`, or boolean (if you pass true, `tree` is the default).
- [x] ([#5763](https://github.com/quarto-dev/quarto-cli/issues/5763)): Add support for a keyboard shortcut to launch search (defaults to `s`, `f` or `/`). Use `search` > `keyboard-shortcut` to override with your own key(s).
- [x] ([#7796](https://github.com/quarto-dev/quarto-cli/issues/7796)): Allow providing placeholder text using the language key `search-text-placeholder`
- [x] ([#5389](https://github.com/quarto-dev/quarto-cli/issues/5389)): Allow a website project to provide a default image used in social metadata tags.
- [x] ([#5251](https://github.com/quarto-dev/quarto-cli/issues/5251)): Allow individual pages to specify `image: false` to prevent image discover for Twitter and Open Graph metadata.
- [x] ([#5624](https://github.com/quarto-dev/quarto-cli/issues/5624)): Add support for localized Cookie Consent (using either the document's language or by specifying the language explicitly under the cookie consent key).

## Jupyter

- [ ] Added `ipynb-shell-interactivity` option (enables specification of IPython [`InteractiveShell.ast_node_interactivity`](https://ipython.readthedocs.io/en/stable/config/options/terminal.html#configtrait-InteractiveShell.ast_node_interactivity) option)
- [ ] Support for `plotly-connected` option to determine where Plotly is embedded or loaded from CDN

## Author and Affiliations

- [x] ([#5764](https://github.com/quarto-dev/quarto-cli/issues/5764)): Add support for affiliations to include a `group` property to represent the team or research group within the affiliation
- [x] ([#6138](https://github.com/quarto-dev/quarto-cli/issues/6138)): Add support for `degrees` to specify academic titles or professional certifications displayed following a personal name (for example, "MD", "PhD").

## Lua filters

- [ ] Add support for relative paths in `require()` calls.
- [ ] Add support `quarto.doc.add_resource` and `quarto.doc.add_supporting`. `add_resource` will add a resource file to the current render, copying that file to the same relative location in the output directory. `add_supporting` will add a supporting file to the current render, moving that file file to the same relative location in the output directory.
- [X] ~([#5242](https://github.com/quarto-dev/quarto-cli/issues/5242)): Add line numbers to error messages.~
- [X] ~([#5461](https://github.com/quarto-dev/quarto-cli/issues/5461)): ensure return type of `stripTrailingSpace` is always `pandoc.List`.~
- [X] ~([#5466](https://github.com/quarto-dev/quarto-cli/issues/5466)): Provide global environment `_G` to user filters.~
- [X] ~([#6211](https://github.com/quarto-dev/quarto-cli/pull/6211)): Improve error message when a JSON filter (or a potentially misspelled Lua filter from an extension) is not found.~
- [ ] ([#6215](https://github.com/quarto-dev/quarto-cli/issues/6215)): Add `quarto.utils.string_to_inlines` and `quarto.utils.string_to_blocks` to Lua API to convert a string to a list of inlines or blocks taking into account quarto's AST structure.
- [X] ~([#6289](https://github.com/quarto-dev/quarto-cli/issues/6289)): allow `markdownToInlines` to take empty string.~
- [ ] ([#6935](https://github.com/quarto-dev/quarto-cli/issues/6935)): Add isGithubMarkdownOutput() to quarto.format API.
- [ ] ([#6935](https://github.com/quarto-dev/quarto-cli/issues/6935)): render callouts to `gfm` using GitHub's syntax.
- [ ] ([#7083](https://github.com/quarto-dev/quarto-cli/issues/7083)): Separate custom node handlers for Span and Div nodes, enabling conditional content spans (author: @knuesel)

## Other Fixes and Improvements

- [X] ~Support `--output-dir` for rendering individual files.~
- [ ] ([#1237](https://github.com/quarto-dev/quarto-cli/issues/1237)): Allow `include` shortcodes to be resolved from inside non-executable code cells and metadata blocks.
- [ ] ([#4820](https://github.com/quarto-dev/quarto-cli/issues/4820)): Add support for setting the Giscus light/dark themes.
- [X] ([#5755](https://github.com/quarto-dev/quarto-cli/pull/5755)): Allow document metadata to control conditional content.
- [ ] ([#8086](https://github.com/quarto-dev/quarto-cli/issues/8086)): Add support for indexing array metadata in `meta` shortcode.
- [ ] ([#1173](https://github.com/quarto-dev/quarto-cli/issues/1173)): Allow specifying margin caption location on a per cell basis

**Comment by cscheid** [comment]
## Lua

I think a number of these don't need explicit documentation. I don't want to add the checkbox myself, but I wouldn't worry about #5242, #5461, #5466, #6211, #6289.

I _do agree_ that #6215, #6935, and #7083 could use documentation.

**Comment by cwickham** [comment]
Closing in favor of issues opened for individual sections/items.
