### ISSUE TITLE
1.4 Changelog Updates: Lua Filters 

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#8301]
Moving from https://github.com/quarto-dev/quarto-cli/issues/7906

Leaving up to @cscheid if and where these are documented:

## Lua filters

- [ ] Add support for relative paths in `require()` calls.
- [ ] Add support `quarto.doc.add_resource` and `quarto.doc.add_supporting`. `add_resource` will add a resource file to the current render, copying that file to the same relative location in the output directory. `add_supporting` will add a supporting file to the current render, moving that file file to the same relative location in the output directory.
- [X] ~([#5242](https://github.com/quarto-dev/quarto-cli/issues/5242)): Add line numbers to error messages.~
- [X] ~([#5461](https://github.com/quarto-dev/quarto-cli/issues/5461)): ensure return type of `stripTrailingSpace` is always `pandoc.List`.~
- [X] ~([#5466](https://github.com/quarto-dev/quarto-cli/issues/5466)): Provide global environment `_G` to user filters.~
- [X] ~([#6211](https://github.com/quarto-dev/quarto-cli/pull/6211)): Improve error message when a JSON filter (or a potentially misspelled Lua filter from an extension) is not found.~
- [ ] ([#6215](https://github.com/quarto-dev/quarto-cli/issues/6215)): Add `quarto.utils.string_to_inlines` and `quarto.utils.string_to_blocks` to Lua API to convert a string to a list of inlines or blocks taking into account quarto's AST structure.
- [X] ~([#6289](https://github.com/quarto-dev/quarto-cli/issues/6289)): allow `markdownToInlines` to take empty string.~
- [ ] ([#6935](https://github.com/quarto-dev/quarto-cli/issues/6935)): Add isGithubMarkdownOutput() to quarto.format API.
- [ ] ([#6935](https://github.com/quarto-dev/quarto-cli/issues/6935)): render callouts to `gfm` using GitHub's syntax.
- [ ] ([#7083](https://github.com/quarto-dev/quarto-cli/issues/7083)): Separate custom node handlers for Span and Div nodes, enabling conditional content spans (author: @knuesel)

**Comment by cwickham** [comment]
@cscheid Let's get this closed for 1.5. I'm happy to take a stab if you help me find homes.

I checked off the last one ([#7083](https://github.com/quarto-dev/quarto-cli/issues/7083)) since we do document conditional spans as part of [Conditional Content](https://quarto.org/docs/authoring/conditional.html#content-visible).

That leaves:
>  Add support for relative paths in `require()` calls.

I'm assuming this belongs somewhere in https://quarto.org/docs/extensions/lua-api.html Maybe as a mention in https://quarto.org/docs/extensions/lua-api.html#lua-base-api?

> Add support `quarto.doc.add_resource` and `quarto.doc.add_supporting`. `add_resource` will add a resource file to the current render, copying that file to the same relative location in the output directory. `add_supporting` will add a supporting file to the current render, moving that file file to the same relative location in the output directory.

These need to go in https://quarto.org/docs/extensions/lua-api.html#quarto-lua-api Do they go:
* In the table at the start of [Dependencies](https://quarto.org/docs/extensions/lua-api.html#dependencies), or
* In their own subsection of Dependencies, or
* ?

**Comment by cwickham** [comment]
On: 
> Add support for relative paths in require() calls.

Is this describing the same thing:  https://quarto.org/docs/prerelease/1.4/lua_changes.html#relative-paths-in-require-calls ? Can we grab this and chuck it wherever we decide from above?

**Comment by cscheid** [comment]
> > Add support for relative paths in require() calls.
> 
> Is this describing the same thing: https://quarto.org/docs/prerelease/1.4/lua_changes.html#relative-paths-in-require-calls ? Can we grab this and chuck it wherever we decide from above?

Yes, and yes.

**Comment by mcanouil** [comment]
I don’t see the new LUA filter processing order in this issue or in the main documentation, am I missing something?

> - https://quarto.org/docs/extensions/filters.html
> - https://quarto.org/docs/prerelease/1.4/lua_changes.html#more-precise-targeting-of-ast-processing-phases (not yet part of the main documentation page)

**Comment by cwickham** [comment]
@mcanouil It's in a [different issue](https://github.com/quarto-dev/quarto-cli/issues/7900), but I'll attack them together

**Comment by cwickham** [comment]
All of these are covered by https://github.com/quarto-dev/quarto-web/pull/1899, except:

([#6935](https://github.com/quarto-dev/quarto-cli/issues/6935)): Add isGithubMarkdownOutput() to quarto.format API.

However, this is equivalent to `quarto.doc.is_format("gfm")` and `quarto.doc.is_format()` is documented, so I don't think anything needs adding.
