### ISSUE TITLE
Epic: Reference Pages 

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#9093]
- [ ] https://github.com/quarto-dev/quarto-cli/issues/6889
- [ ] https://github.com/quarto-dev/quarto-cli/issues/6858
- [ ] https://github.com/quarto-dev/quarto-cli/issues/6061
- [ ] https://github.com/quarto-dev/quarto-cli/issues/5352
- [ ] https://github.com/quarto-dev/quarto-cli/issues/5187
- [ ] https://github.com/quarto-dev/quarto-cli/issues/5109
- [ ] https://github.com/quarto-dev/quarto-cli/issues/1531
- [ ] https://github.com/quarto-dev/quarto-cli/issues/598
