### ISSUE TITLE
Epic: Extensions Section

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#9094]
- [ ] https://github.com/quarto-dev/quarto-cli/issues/8301
- [ ] https://github.com/quarto-dev/quarto-cli/issues/7900
- [ ] https://github.com/quarto-dev/quarto-cli/issues/5194
- [ ] https://github.com/quarto-dev/quarto-cli/issues/4926
- [ ] https://github.com/quarto-dev/quarto-cli/issues/4499

**Comment by cwickham** [comment]
Moving some comments out of #7900:

> I've seen many users using Lua filters without using Quarto extensions mechanism.
I think some users don't know they don't have to write extensions to use a Lua filter (especially all the Lua filters developed initially for Pandoc).

> Here the "Extensions" pages should be read as "Extend Quarto with Lua filters, shortcodes formats and possibly distribue as Quarto extensions" but I feel users are reading this as "Use Quarto Extension mechanism", especially since this part starts with a listings of extension followed by how to create extensions.

> (my two cents)

> FYI, in discussions, there are several simple examples of Lua filters (a lot written by @cscheid):
> - https://github.com/quarto-dev/quarto-cli/discussions/7526#discussioncomment-7523579
> - https://github.com/quarto-dev/quarto-cli/discussions/7864#discussioncomment-7820858
> - https://github.com/quarto-dev/quarto-cli/discussions/7313#discussioncomment-7347263
> - https://github.com/quarto-dev/quarto-cli/discussions/6550#discussioncomment-6753032
> - https://github.com/quarto-dev/quarto-cli/discussions/6111#discussioncomment-6365798

> https://github.com/quarto-dev/quarto-cli/discussions?discussions_q=label%3Alua

_Originally posted by @mcanouil in https://github.com/quarto-dev/quarto-cli/issues/7900#issuecomment-1852907886_
